### ISSUE TITLE
Top-level manual organization

### ISSUE THREAD

**Issue by acabal** [standardebooks/manual#1]
Right now the manual is pretty small compared to its final size, and it's still a pain to edit. I think it would be a lot easier to edit if we split it into several files, one for each top-level section.

Of course that begs the question, what would the top-level sections be?

Right now, the ones I have started are:

1. XHTML and CSS code formatting style (code style basics)
2. Filesystem layout (Rules for filenames, where each file goes, types of required files, etc.)
3. Semantic inflection (basics, vocabularies, etc.)
4. General XHTML patterns (general rules that are too broad to be in other sections)
5. Sectioning
6. Parts of an ebook (describe what is frontmatter, how an intro differs from a foreword, etc.)
7. Headers
8. TBD....

Should we keep these sections as they are? Rearrange anything? What would come next for #8 and onwards?

**Comment by scriptdaemon** [comment]
Would it make enough sense to have the meat of the document be in markdown, and then compiled to HTML during the build step that adds it to the website? That might make editing a bit less tedious.

**Comment by drgrigg** [comment]
I'm a big Markdown fan, so I would generally be in favour. That said, however. there are portions of the existing manuals with HTML and CSS examples, syntax highlighted. I don't think you could easily represent those in Markdown without it becoming very messy.

**Comment by scriptdaemon** [comment]
I don't know about other implementations, but GitHub's allows HTML inside markdown. So for those portions, they could stay as HTML.

**Comment by robinwhittleton** [comment]
I’m not too fussed about how it’s split, but I think a stated goal should be that it mostly tries to appeal to new starters. People who’ve already got a book or three under their belt can jump in and out easily (e.g. I mostly use the step-by-step guide, the typography page for specific requirements and the SE vocabulary). So I’d go for introduction - prerequisites - tutorial - reference as a layout. So, something like:

1. Introduction and welcome
2. A quick overview of the epub ebook format
3. Required skills and how to acquire them
4. Producing an ebook step by step
5. Typography
6. Content semantics
7. Choosing and producing artwork
8. A deep dive into the EPUB3 format (ToC, content.opf, x-matter declarations + sectioning etc)

**Comment by acabal** [comment]
The way I'm envisioning the manual is kind of like a Chicago Manual of Style type thing. That is, a generic series of style rules that result in a generic, high quality ebook with a certain typographical style and a few necessary SE-specific documents like imprint and cover/title images. Not necessarily as a how-to for making an SE ebook, or a how-to for making an epub ebook. So for example a different publisher might be able to take the manual and produce a good ebook in their own format.  (After excluding some SE-specific stuff.)

With that in mind, I want to separate the style manual from the SE-specific guides and steps. How-tos for SE productions would be in separate documents, like the step-by-step guide. I think art tips and tricks (i.e. handy lessons learned from doing PD research, PD research resources, etc.)  should also go in a separate document; but style rules on what constitutes an SE cover and title page belong in the manual.

I also don't want to be teaching people how to make epubs in our document, because 1. the epub spec will change and that's less for us to maintain, and 2. there are better places to learn how to make epubs and it's not hard to do the research on one's own.

In other words, the manual *defines* what an ebook produced to the SE style *looks like*, in declarative language like "Non-English words and phrases are italicized." How to *actually produce it* and *general epub spec information* goes in other documents.

If any of you have a Chicago Manual of Style on hand, thumb through that to get an idea of what I'm thinking of. In fact I should browse through mine to see how they divided their top level sections...

Our existing typography and semantics manuals are already very much in the style I'm thinking of. The problem is that many questions cover a grey area of both worlds. For example, it's easy to say that non-English words are italicized as a matter of typography. But then why flip to a different manual to learn that when italicizing, as a matter of semantics we use the `<i>` tag and with specific `xml:lang` attributes from a specific language tag vocabulary? Better to have all of that in one single manual.

That's what I'm getting at; merging these two, and then filling them out with other rules that we're following in live ebooks but haven't written down yet. (Letter formatting, plays and dialog, etc. etc.)

**Comment by drgrigg** [comment]
I've been thinking about this, and I like the idea of an SE Style Manual. I'm familiar with such manuals from my time as a journalist.

You've already covered this, but to re-state it : we need to turn it around -- rather than sections on how to handle italics, dashes, etc as the current manuals do, start with **how we want the book to look** and then prescribe how to do that, piece by piece.

**Comment by acabal** [comment]
How about something like the below. (This drills down a little deeper than top-level but I think it's helpful to see what might be included below the top level.)

- XHTML and CSS code formatting style (code style basics)
- Filesystem layout (Rules for filenames, where each file goes, types of required files, etc.)
- Parts of an ebook (describe what is frontmatter, how an intro differs from a foreword, etc.)
- Semantic inflection (basics, vocabularies, etc.)
- General XHTML patterns (general rules that are too broad to be in other sections: rules for attributes, ids, title tags, ul/li, blockquote, hr, etc.)
- Sectioning (how to use section tags, recomposability, front/backmatter, half titles)
- Table of Contents rules
- Common semantic patterns
	- Headers
	- Poetry/verse
	- Plays
	- Letters
	- Images (as represented in text; SVG code formatting in different section)
		- LoI
	- Endnotes
- Images (internal requirements for SVG format)
- Typography
	- Spacing (no double space, indentation rules)
	- Names and titles
		- Capitalization
		- Italics or quote
		- Other rules (remove archaic double quotes, etc.)
	- Capitalization
		- In titles
		- In proper names
	- Italics
		- When to use vs quotes
		- Other rules
		- Latinisms (new: list of latinisms to italicize vs not)
	- Punctuation (quotation marks, ellipses, periods within quotation marks, dashes, etc.)
	- Numbers and math
	- Miscellenea like times, chemicals, abbreviations, initialisms, etc.

A lot of this is just a 1:1 merging of the current semantics and typography manuals. I think once we at least merge them as a rough draft, this will give us a better idea of how to reorganize things, if we want. What do you all think?

**Comment by acabal** [comment]
OK, I wanted to step in and revitalize this project a little, because as we're getting more and more contributors and `lint` is becoming more complex, I think it's important to complete the "single manual" vision with numbered rules we can point to both in `lint` and during the review process.

I've gone ahead and broken up the manual into the sections I've suggested. `manual.html` is the table of contents. Now I need your guys help to flesh them out!

Some of the sections are more or less complete, like the code style one. Others are nonexistent or sloppy. (ToC, typography).

I need your help to work on this; I've already put a huge amount of time into this manual and my real life is getting very busy at the moment, let alone all of the other SE managing work I have to do.

So what I want to do right now is be a little presumptuous and assign you each some tasks in the Github project view. If you don't have interest or time that's totally fine, just let me know and I'll remove you. Or if you'd prefer to contribute in some different way to the manual, just let me know. But for now I think it's important to have some goals and tasks set up that we can work towards, to make this manual a great resource for everyone to be able to refer to.

Remember that these files are extremely rough, and there's a lot of copy-paste. Let's not worry about the final formatting for now, we'll address that later.

Any suggestions for a better way to edit his (maybe a different documentation-based markup language?) are welcomed!
