### ISSUE TITLE
Internal thoughts

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/manual#10]
In an email exchange last year on the list, you mentioned that internal thoughts that are italicized in the source should probably just be unsemanticated `<i>`. That’s not in the italics section in the manual; would you like a PR to add it? I've had this in a couple of books, and it just came up in a book I reviewed, so I think it happens enough that it would be helpful for it to be in the manual.

**Comment by acabal** [comment]
Yes, sure. Thanks!
