### ISSUE TITLE
Example used in 8.10.9.4 contradicts 8.10.9.5

### ISSUE THREAD

**Issue by alvbd** [standardebooks/manual#117]
The Australian Broadcasting Corporation is (now) stylised as "ABC", not "A.B.C."

Also, should a text written when the ABC was stylised as "A.B.C." be modernised to "ABC"? Or should modernisation only follow general English usage and not the whims of marketing departments?

**Comment by acabal** [comment]
I think your point about marketing departments is a good one. The A.B.C. has been around for quite a long time; our own style treats initialisms in a particular way; and we're not going to try to track the whims of whatever marketing department is in charge of whatever company at some particular point in time. Thus, we should leave it as it is in the manual.
