### ISSUE TITLE
`eoc` needed in example letter?

### ISSUE THREAD

**Issue by dajare** [standardebooks/manual#122]
One of the example letters ([§ 7.7.3.5.1][1]), signed "Edward Gardner", includes this @ line 1192 (of the raw .rst file):

`<p epub:type="z3998:valediction">Yours, <abbr>etc.</abbr></p>`

Should this `<abbr>` also include `class="eoc"`? or does this type of paragraph not need the `class`?
 
[1]: https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.7.3.5.1

**Comment by acabal** [comment]
Thanks, I've added it!
