### ISSUE TITLE
Section 5.10 contains a "wrong" example but the "corrected" example is not visible

### ISSUE THREAD

**Issue by eileenh** [standardebooks/manual#135]
Here's what I'm seeing in version 1.7.0:
![image](https://user-images.githubusercontent.com/8673424/221448449-812d1ceb-a0e3-45d8-9b27-d269187b7802.png)

It looks like there's a 'corrected' example in the page source but I'm not sure why it's not showing up

**Comment by acabal** [comment]
Thanks, this should be fixed now!
