### ISSUE TITLE
Header inconsistency in Section 7.2.3

### ISSUE THREAD

**Issue by apasel422** [standardebooks/manual#142]
Section [7.2.3](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.2.3) says:

> The book’s title is implicitly at the `<h1>` level, even if `<h1>` is not present in the ebook. An `<h1>` element is only present if the ebook contains a half title page. Because of the implicit `<h1>`, all other sections begin at `<h2>`.

But [6.3.3](https://standardebooks.org/manual/1.7.3/6-standard-ebooks-section-patterns#6.3.3) says that the title page uses `<h1>` and [6.5.4](https://standardebooks.org/manual/1.7.3/6-standard-ebooks-section-patterns#6.5.4) says that the half title page uses `<h2>`.

**Comment by acabal** [comment]
Thanks, has been fixed in the next version.
