### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by shimizurei** [standardebooks/manual#143]
[8.4.2](https://standardebooks.org/manual/1.7.3/single-page#8.4.2)

The first line of body text in a section, or any text following a visible break in text flow (like a header, a scene break, a **figurem** etc.), is not indented, with the exception of block quotations.

---

[8.14.1](https://standardebooks.org/manual/1.7.3/single-page#8.14.1)

When scansion marks are next to, instead of above, letters, `×` (U+00d7) indicates an unstressed **sylllable** and...

I was just reading the manual to see what this project was about and I saw these. Have a great day!

**Comment by acabal** [comment]
Thanks, these should be fixed now!
