### ISSUE TITLE
Should fulltitle file-as reference the fulltitle?

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/manual#145]
https://github.com/standardebooks/manual/blob/064e5dee8be8e79ed0cfe7a16349af5ddee7e38e/9-metadata.rst?plain=1#L103-L105

This feels like a bug, but I want to check. Line 104 should be the following right?

```
<meta property="file-as" refines="#fulltitle">Man Who Was Thursday: A Nightmare, The</meta> 
```

**Comment by acabal** [comment]
No, because it's just the file-as. I don't think subtitles are typically included when sorting titles for filing.
