### ISSUE TITLE
HTML5: <cite> must not be used to mark up people’s names

### ISSUE THREAD

**Issue by bentley** [standardebooks/manual#146]
This one’s a doozy. [According to the current HTML5 spec](https://html.spec.whatwg.org/#the-cite-element), `cite` must not be used for people’s names. In fact, `cite` may be used for titles of works mentioned in passing, not just citations.

This contradicts several examples from the manual:

- [7.4.5.1: `<cite>Chaucer</cite>`](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.4.5.1)
- [7.10.5.3: `<cite>—<abbr class="eoc" epub:type="z3998:personal-name">W. T. G.</abbr></cite>`](https://standardebooks.org/manual/1.7.3/7-high-level-structural-patterns#7.10.5.3)
- [8.2.13.1: `<cite><i epub:type="se:name.publication.book">Maximes</i>, <i xml:lang="la">fr</i> <abbr epub:type="z3998:given-name">M. G.</abbr> De Levis.</cite>`](https://standardebooks.org/manual/1.7.3/8-typography#8.2.13.1)
- [8.5.2.1: `<cite>Chaucer</cite>`](https://standardebooks.org/manual/1.7.3/8-typography#8.5.2.1)
- Pretty much the entire first part of 8.17

And given the examples in the spec, it seems that [8.2.11.2](https://standardebooks.org/manual/1.7.3/8-typography#8.2.11.2) would be updated to italicize titles using `cite`.

**Comment by acabal** [comment]
Yes, we're just going to ignore that for now. I don't think that is a useful definition of the element and updating the corpus would be too much work right now.
