### ISSUE TITLE
Should hair spaces be allowed in alt attributes?

### ISSUE THREAD

**Issue by apasel422** [standardebooks/manual#163]
https://standardebooks.org/manual/1.8.0/7-high-level-structural-patterns#7.8.2.1.1 says:

> The `alt` attribute does not contain no-break spaces or word joiners.

But should that attribute ever contain a hair space?

**Comment by acabal** [comment]
Yes, it can include exotic spacing and punctuation. It does not include nbsp or wj because for the most part there is no concept of a line break in an alt attribute, and those two characters specifically control line breaking.
