### ISSUE TITLE
Standardise usage of 8vo (4to, 16mo, etc)

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/manual#167]
Our corpus has varied uses of `8vo`, `8vo.`, `<abbr>8vo</abbr>` and `<abbr>8vo.</abbr>`. Should we add something to the abbreviations section about it?

(I don’t have a recommendation one way or another on this really.)

**Comment by acabal** [comment]
Yes, that would sense. I think `<abbr>8vo</abbr>` would be the way to go.
