### ISSUE TITLE
Link rot for CMofStyle 16

### ISSUE THREAD

**Issue by ableal** [standardebooks/manual#172]
In the manual pages (a) the link (b) for  "Chicago Manual of Style, 16th edition" has rotted, and now yields a page not found message.

a) https://standardebooks.org/manual/1.8.0  and https://standardebooks.org/manual/1.8.0/single-page 
b) https://www.chicagomanualofstyle.org/16/contents.html

The CMOS site seems to have moved to v18 in 2024, and now only supplies a link to v17 upfront. I did not investigate fully if v16 is somehow still available.

Thanks for the magnificent, and munificent, work.

**Comment by acabal** [comment]
Thanks, this has already been fixed in the `next` branch so it will be fixed in the next version of the manual.
