### ISSUE TITLE
Getting the manual into a working state.

### ISSUE THREAD

**Issue by scriptdaemon** [standardebooks/manual#2]
So I finally had some time to clone this, and attempted to open the html file in Firefox to view it in order to see where to begin contributing. First thing seems to me to get this repository into a working state (one that "just works" from the initial clone, so the developer doesn't have to download jQuery, etc. manually. This way any future changes are easy to see (currently syntax highlighted text is unreadable, etc.), and the document itself is easier to update.

I assume once jQuery and the plugins and theme are put in the appropriate places, the html should be fully readable? Is there a reason those hadn't been added to the repository to begin with, or is that something that just hasn't been done yet? Do you oppose to them being added to the repository? If yes, do you think a build system using npm to install the dependencies would be overkill for this project (I'm more than willing to do it, if you're open to it)?

**Comment by acabal** [comment]
That's just a combination of the manual being in a very rough draft state, and my own laziness. Jquery is only required for code highlighting. I'll add most of that stuff in to the repo shortly.

**Comment by acabal** [comment]
OK everything except the header image should be in the repo now. Again we're not aiming for actual readability yet, just a general structure and filling out the manual before we decide on better presentational styling.
