### ISSUE TITLE
Differentiating between poem and verse, song and hymn

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/manual#24]
Should we add something to [7.5.6](https://standardebooks.org/manual/1.1.1/7-high-level-structural-patterns#7.5.6) that indicates when to use verse and when to use poem? What's been mentioned on the list is that `verse` is for partial quotes of a poem and `poem` is for when a full poem is quoted. And I know what a hymn is (well, in my context anyway), but I don't  know that I've ever seen anything on the list about when to use which (`hymn` vs `song`).

I'll write something up if need be; would you want it on 7.5.6, or as a sub-item, i.e. 7.5.6.1, etc.? (I just noticed the other issue I raised about internal thoughts; I'll do that tonight, I had forgotten about it.)

**Comment by acabal** [comment]
Sure. Usually I prefer to leave questions about other specs (in this case z3998) to the other specs, but z3998 doesn't elaborate on their terms. As you mentioned, poem is for complete poems (even short ones), verse is for fragments of poems/verse. Song vs hymn probably boils down to whether or not it's a religious composition, though in practice I think we've only ever used hymn when the text explicitly calls out a blockquote as a hymn.  You can add it as a sub-item, I think.
