### ISSUE TITLE
Flesh out and complete parts-of-a-book.html

### ISSUE THREAD

**Issue by acabal** [standardebooks/manual#3]

**Comment by drgrigg** [comment]
Ok, will look into this shortly.

**Comment by acabal** [comment]
I'm trying out Github projects: https://github.com/standardebooks/manual/projects/1

Can you move the card to in progress once you start? Let's see if this projects interface is helpful to managing things.

**Comment by drgrigg** [comment]
A question about how to approach this: am I describing the structure of specifically **Standard Ebooks** works or a more general description? For example, in your rough outline of this page, you've specifically listed Acknowledgements in the frontmatter section; but many authors (including me) put their Acknowledgements at the end, not the start of a book. I can imagine the same might apply to say, a Glossary. Again, many if not most books put the List of Illustrations at the start, but SE puts it into backmatter.

I think I'd rather talk about frontmatter, bodymatter and backmatter in general terms first, then separately go through a list of the various component parts of a book, noting appropriately where these parts generally fall, with exceptions set out about how SE treats them (such as your note about the copyright part).

Would that be OK?

**Comment by drgrigg** [comment]
I would also have thought that a Prologue would be part of bodymatter as it's usually part of the story itself, just like a preliminary chapter, and may introduce characters, subsidiary plot lines, etc. The EPUB 3 Structural Semantics guide lists it as typically part of bodymatter.

**Comment by acabal** [comment]
Sure, I think that's a good approach. Describe what front/body/backmatter is in a general sense, then list the common book partitions and at the end of each add a tag for what they potentially could be categorized as.

Something like: `Acknowledgements: A list of people that the author wishes to thank. Pertains to: frontmatter, backmatter.`

Of course some things will always be frontmatter, like full-page dedications.

As you noted however since this is the SE manual we do want to define specific parts with regards to the SE standard. So things like the titlepage, imprint, colophon, (un)copyright page, etc., would be defined as how we do them. I.e. the copyright page is backmatter, the imprint contains SE-specific info, etc.

For a lot of these definitions it's a matter of taste and style. It might also be a good idea to add a numbered directive saying that there's also lots wiggle room for case-by-case exceptions.

**Comment by acabal** [comment]
BTW as you convert to RST please see how I've done existing sections. In particular use `#.` for numbered directives as they become auto-numbered; and set the `.. class:: data-start-at-#` special directive after the `h1` element to match the ToC. (In this case # would be 3.)

**Comment by drgrigg** [comment]
Ok, no problem. I'm still feeling my way with this RST stuff, so I probably shouldn't commit anything again until I've become a bit more adept!

**Comment by drgrigg** [comment]
I've finally completed the (probably very rough) first draft of this. I felt compelled to change the title and thus file name to "The Structure of an Ebook".

I think you'll want to dispute with me about my characterisations of 'Introduction', 'Prologue' and 'Epilogue' which I'm saying should be part of bodymatter. We haven't treated them that way in previous SE productions, but I really think from everything I read online that they should be so treated. We can discuss!
