### ISSUE TITLE
Common issues

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/manual#36]
I have the start of a Common Issues file. For now, I've just used the same formatting as the manual, because it was in front of me and easy to structure and have the formatting for bash, wrong and corrected examples, etc. We can regex it to adjust it to whatever we want as we go on.

Where would you like me to put it? Matt mentioned wanting to help with it as well.

**Comment by acabal** [comment]
You can create a new branch and start a pull request for now. We can massage it there for a while.

**Comment by vr8hub** [comment]
Done.

**Comment by acabal** [comment]
Closed in favor of #37
