### ISSUE TITLE
document En dashes and word joiners

### ISSUE THREAD

**Issue by davidscotson** [standardebooks/manual#39]
In the documentation on en- and em-dashes, the use of word-joiner unicode characters is mentioned in conjection with em dashes, but not mentioned, or used in the examples given, for en dashes, e.g. ranges of numbers:

https://standardebooks.org/manual/1.0.0/8-typography#8.7.7

But `se typogrify` will add word-joiners on both sides on en dashes, according to this comment:
https://github.com/standardebooks/tools/blob/master/se/typography.py#L89-L90

and this appears to be the intended behaviour (to keep both parts of the en-dashed range together, and not line break in the middle of them). So presumably the documentation needs updated to match the tooling.

I spotted this because my current ebook reading software got confused by these invisible characters, and reversed the order of the two numbers either side of the en-dash, but that appears just to be a bug in their code, it doesn't happen with any other ereader software I've tested so far.

**Comment by acabal** [comment]
This is fixed in f750937, thanks!
