### ISSUE TITLE
Flesh out high-level-structural-patterns.rst

### ISSUE THREAD

**Issue by acabal** [standardebooks/manual#4]
This will be a big job, so it might be best to split it amongst a few people. Kenny, maybe you can start out with fleshing out the first three list items on that page. Headers is already in there, poetry and verse can largely be copy and paste from the existing manual; plays has the raw code at the end of the document and needs formatting and fleshing out.

Robin, can you work on letters, images, LoI, endnotes? Images/LoI/Endnotes are partially copy and paste. Letters is a new section but you know how those are formatted by now, so you can really go into detail with how to do that.

**Comment by acabal** [comment]
BTW this is a great opportunity to write down any and all conventions we've been working on, but that aren't yet "official", so we can point other producers to them. And if you want to include anything that's not on that bullet list, we can get that added to. Those are just the examples that came up off the top of my head.

**Comment by scriptdaemon** [comment]
Just got back from vacation (in case you've noticed a lack of activity over the last few days). Hopefully I can manage some time tonight to get started.

**Comment by robinwhittleton** [comment]
Did an endnotes section from scratch forgetting that we already had one in the docs 🤦‍♂️ Will copy the images and LoI sections over, then revisit the endnotes to make sure I’ve captured everything.
