### ISSUE TITLE
Using reStructuredText for documentation

### ISSUE THREAD

**Issue by acabal** [standardebooks/manual#5]
Editing these raw HTML files is really cumbersome for technical documentation, not least of all because we have to escape `<` and `>`, and indentation levels in preformatted code blocks is a pain.

I've been investigating using reStructuredText instead. Check out the new [rst branch](https://github.com/standardebooks/manual/tree/rst) of this repo, and look at the file `code-style.rst`. The `build-docs` takes that file and generates `code-style.html`.

What do you all think of that process instead? IMHO while RST isn't perfect it's much easier to work with than the raw HTML.

**Comment by drgrigg** [comment]
I must admit I've hesitated to get started on my assignment because of this issue -- looked at trying to copy the template into Word but ugh!

But why not simply use Markdown? I'm not familiar with restructured text, but it looks very similar to Markdown but with less general support.

**Comment by acabal** [comment]
I looked at Markdown but the problem is that it does not support things like inline code blocks, and some other features we would need like tables and the occasional custom CSS class are clunky or impossible. Markdown was meant as a readable alternative to most plain text uses, but RST was specifically meant as a readable alternative for technical documentation.

RST does have plenty of support (I was able to install a compiler with syntax highlighting in 2 commands) it's just that it's such a niche target audience that you rarely hear about it. For example all of the Python documentation (which is a lot!) is written in RST and then compiled to HTML.

I've done some additional conversions (`art.html`, `filesystem.html`) and I'm liking it so far. It is definitely much less tiresome than composing raw HTML. Take a look at those RST files and see what you think.

**Comment by drgrigg** [comment]
OK, but I'll need some time to get up to speed with RST syntax. 

In particular, what tool are you using to compile RST to HTML? I tried the docutils rst2html tool, but it seems to put a vast amount of weird CSS in there.

**Comment by acabal** [comment]
See the `build-docs` script in this repo.

````
sudo pip3 install rst2html5
rst2html5 --stylesheet=css/monokai.css test.rst > test.html
````

That's pretty much all there is to it.

**Comment by drgrigg** [comment]
Oh yeah, that's MUCH nicer. Thanks!

**Comment by acabal** [comment]
I've finished converting a handful of the existing manual pages and I think RST is by far a much nicer format. So let's use it as the official one for now. I'll work on converting some of the remaining manual pages. David, since you're working on the Parts of an Ebook page, which in its currenet state is fairly short, maybe you can convert that one, using my existing conversions as a guide.

Note the characters used for the different section headers, and that we want to use `#.` to number list items automatically. (One of the goals of the manual is to be able to point to particular directives by their number, like "look at SE 5.3.1.1".)
