### ISSUE TITLE
Varying uses of the term "elision" in step 8 of the step-by-step guide

### ISSUE THREAD

**Issue by bound-variable** [standardebooks/manual#68]
Step 8 contains the following two dictates:

- **Elision**. ’ (i.e., &rsquo;) is used for elided letters in a word. se typogrify often gets this wrong, and you need to review your ebook by hand to ensure it didn’t insert ‘ (&lsquo;) instead.
- Two-em dashes should be used for **elision**.

I was told the second reference of **elision** is actually referring to "**partially obscured words**".

If so, why not clarify this by replacing the second mention of "elision" with "partially obscured words"?

**Comment by acabal** [comment]
Thanks, this should be fixed now!
