### ISSUE TITLE
Initialisms rule is unclear, possible typo

### ISSUE THREAD

**Issue by mgbennet** [standardebooks/manual#7]
[Rule 8.10.2](https://standardebooks.org/manual/1.0.0/8-typography#8.10.2) states "Initialisms (terms made up of initials in which each initial is pronounced separately, like ABC, HTML, or CSS) are set with without periods (with the following exceptions)..." So is that with periods, or without periods? I assume there's a missing 'or' between 'with' and 'without'. And what are the following exceptions? The ones in 8.10.4?

**Comment by acabal** [comment]
Good catch. This was a recent update to bring back periods to initialisms and it looks like I messed that part of the manual up. I've updated it so that it should be clear now. Thanks!
