### ISSUE TITLE
Style guide is silent on modernizing spelling

### ISSUE THREAD

**Issue by hatchetation** [standardebooks/manual#89]
Several of the contribution guides contain guidance on modernizing spelling. e.g., Step By Step and Reviewing for Production. 

However, it doesn't appear that these directives are formalized in the style guide.

**Comment by acabal** [comment]
Correct, because the style guide is supposed to be a general-purpose style guide that could be reused by other publishers; it's not a "how to make an SE ebook" guide. (Though many of its prescriptions just happen to be conducive to that.)
