### ISSUE TITLE
Fix broken code rendering on macOS Firefox with no local copy of Source Code Pro

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/manual#9]
Something’s weird with our code display in Firefox on macOS: if you don’t have Source Code Pro installed locally it falls back to just black rendering, regardless of CSS.

I’ll have a dig into why this might be happening.

**Comment by robinwhittleton** [comment]
This is https://github.com/adobe-fonts/source-code-pro/issues/217, which links through to https://bugzilla.mozilla.org/show_bug.cgi?id=1520157.

**Comment by acabal** [comment]
What if we just removed the local() part and relied on serving our own copy? Does it work then?

**Comment by robinwhittleton** [comment]
I tried playing around with this and got sidetracked by finding a crashing bug in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1649676 if you’re interested). My feeling is no (local is actually allowing the working copy of Source Code Pro) but I’ll dig into this in more detail tonight to double-check

**Comment by acabal** [comment]
OK. If it doesn't work at all then we can switch to Fira. Maybe you can put together that pull request if you have some free time.
