### ISSUE TITLE
Examples in 7.1.5.1 not consistent with 1.1.7.1?

### ISSUE THREAD

**Issue by weijia-cheng** [standardebooks/manual#92]
The new recomposability examples in [7.1.5.1](https://standardebooks.org/manual/1.6.3/7-high-level-structural-patterns#7.1.5.1) show the new `data-parent` attribute as the last attribute, but alphabetically `data-parent` is before `id` so it should go first according to [1.1.7.1](https://standardebooks.org/manual/1.6.3/1-code-style#1.1.7.1).

If you do follow the manual's example of putting `data-parent` last, running `se clean` moves it first, so it seems either 7.1.5.1 is correct or 1.1.7.1./`se clean` is correct.

**Comment by acabal** [comment]
Thanks, I've fixed this!
